// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBridge.API.DataBase;

#nullable disable

namespace TravelBridge.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TravelBridge.API.Models.DB.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CouponType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<int>("UsageLeft")
                        .HasColumnType("int");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("CHAR(2)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.NextPaymentDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PartialPaymentDBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartialPaymentDBId");

                    b.ToTable("NextPaymentDB", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.OwnedHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CheckInTime")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CheckOutTime")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("DECIMAL(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("DECIMAL(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_OwnedHotel_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_OwnedHotel_IsActive");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_OwnedHotel_Location");

                    b.ToTable("OwnedHotels", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.OwnedInventoryDaily", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("DATE");

                    b.Property<int>("ClosedUnits")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmedUnits")
                        .HasColumnType("int");

                    b.Property<int>("HeldUnits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("DATETIME(6)");

                    b.Property<decimal?>("PricePerNight")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.HasKey("RoomTypeId", "Date")
                        .HasName("PK_OwnedInventoryDaily");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_OwnedInventoryDaily_Date");

                    b.ToTable("OwnedInventoryDaily", null, t =>
                        {
                            t.HasCheckConstraint("CK_OwnedInventoryDaily_Counters", "ClosedUnits >= 0 AND HeldUnits >= 0 AND ConfirmedUnits >= 0 AND (ClosedUnits + HeldUnits + ConfirmedUnits) <= TotalUnits");
                        });
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.OwnedRoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePricePerNight")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DefaultTotalUnits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("int");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotalOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("IX_OwnedRoomType_HotelId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_OwnedRoomType_IsActive");

                    b.HasIndex("HotelId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_OwnedRoomType_HotelId_Code");

                    b.ToTable("OwnedRoomTypes", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.PartialPaymentDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("prepayAmount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PartialPaymentDB", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.PartyItemDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<string>("Children")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PartyItemDB", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateFinalized")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PaymentProvider")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<string>("CheckInTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<string>("CheckOutTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Coupon")
                        .HasColumnType("longtext");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateFinalized")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HotelCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HotelName")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int>("PartialPaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Party")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<byte>("TotalRooms")
                        .HasColumnType("TINYINT UNSIGNED");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartialPaymentId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.ReservationRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardInfo")
                        .HasColumnType("longtext");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("CancelationInfo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateFinalized")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HotelCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int?>("Provider")
                        .HasColumnType("int");

                    b.Property<int>("ProviderResId")
                        .HasColumnType("int");

                    b.Property<byte>("Quantity")
                        .HasColumnType("TINYINT UNSIGNED");

                    b.Property<string>("RateId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int?>("SearchPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SearchPartyId");

                    b.ToTable("ReservationRates", (string)null);
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.NextPaymentDB", b =>
                {
                    b.HasOne("TravelBridge.API.Models.DB.PartialPaymentDB", null)
                        .WithMany("nextPayments")
                        .HasForeignKey("PartialPaymentDBId");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.OwnedInventoryDaily", b =>
                {
                    b.HasOne("TravelBridge.API.Models.DB.OwnedRoomType", "RoomType")
                        .WithMany("InventoryDays")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.OwnedRoomType", b =>
                {
                    b.HasOne("TravelBridge.API.Models.DB.OwnedHotel", "Hotel")
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.Payment", b =>
                {
                    b.HasOne("TravelBridge.API.Models.DB.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelBridge.API.Models.DB.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.Reservation", b =>
                {
                    b.HasOne("TravelBridge.API.Models.DB.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelBridge.API.Models.DB.PartialPaymentDB", "PartialPayment")
                        .WithMany()
                        .HasForeignKey("PartialPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PartialPayment");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.ReservationRate", b =>
                {
                    b.HasOne("TravelBridge.API.Models.DB.Reservation", "Reservation")
                        .WithMany("Rates")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelBridge.API.Models.DB.PartyItemDB", "SearchParty")
                        .WithMany()
                        .HasForeignKey("SearchPartyId");

                    b.Navigation("Reservation");

                    b.Navigation("SearchParty");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.Customer", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.OwnedHotel", b =>
                {
                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.OwnedRoomType", b =>
                {
                    b.Navigation("InventoryDays");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.PartialPaymentDB", b =>
                {
                    b.Navigation("nextPayments");
                });

            modelBuilder.Entity("TravelBridge.API.Models.DB.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
